### PR TITLE
Added HID Bootloader 2.0 support

### PR DESCRIPTION
**Pull request by Serasidis**
HID Bootloader 2.0 supports Bluepill and generic_f407v boards
The hid-flash tool is at the moment available only on Windows

Please update your HID Bootloader firmware to V2.0
(https://github.com/Serasidis/STM32_HID_Bootloader/tree/master/bootloader_F1/bootloader_only_binaries)
(https://github.com/Serasidis/STM32_HID_Bootloader/tree/master/bootloader_F4/bootloader_only_binaries)

### CODE REVIEW

**Comment by chrissbarr** [comment]
This looks pretty cool! Do you plan to release the source for the F4 version at some stage?

**Comment by Serasidis** [comment]
Yes. The source code for F4 will be available soon

**Comment by Serasidis** [comment]
The HID Bootloader v2.0 source code for STM32F407 has been released
https://github.com/Serasidis/STM32_HID_Bootloader/tree/master/bootloader_F4

**Comment by danieleff** [comment]
Tried on f407, works, but will need some description in the upload page: make/download .bin, upload with other upload method, change upload method, test with blink.
Or a link to such explanation page.

**Comment by ChrisMicro** [comment]
Does it also work under Ubuntu?

**Comment by Serasidis** [comment]
@danieleff 
Do you mean a guide on how-to compile and use the HID bootloader ?

**Comment by danieleff** [comment]
I am talking about this page https://danieleff.github.io/STM32GENERIC/upload/#usb-hid-bootloader , added a little explanation how to use it, not much, but it's a start.
Windows only as I can see it.

**Comment by Serasidis** [comment]
Nice !
The **hid-flash** tool is available on Mac and Linux as well. The files are distributed trough the following patch file. 
https://github.com/Serasidis/STM32_HID_Bootloader/blob/master/Arduino_STM32_patch_180809_02.zip

The above patch file is formated for using it with **Arduino_STM32** repo. It needs some modifications to follow the file structure of your repository.

Basically, you only need the files from "tools" folder that have the same structure on both repositories.

**Comment by uzi18** [comment]
is there some pro/cons/features listed for all of these bootloaders?
Please  describe pros/cons in HID bootloader.

**Comment by uzi18** [comment]
ok I have read all needed sources
can't find here patch for **usbd_cdc.c** to write magic into bkp section:
```
				bkp_init();
				bkp_enable_writes();
        *(__IO uint32_t *)(BKP_BASE) = 0x424C;
				bkp_disable_writes();
```

and code checks for minimum 4 dtr pulses, but hid-flash sends only 3 pulses.

**Comment by Serasidis** [comment]
@uzi18 
Good catch uzi18. It seems that I missed to send the changes in the usbd_cdc_if.c file at the previous pull request.

I sent a new pull request.

**Comment by uzi18** [comment]
just add commit to this pull request

**Pull request merged**
