### PR TITLE
TFT buffer size in examples corrected

### PR DESCRIPTION
**Pull request by ChrisMicro**

### CODE REVIEW

**Comment by danieleff** [comment]
I will cherry pick from this request, because the "Merge branch 'master'" commits are unnecessary noise.
Also I don't want 2 commits that just remove then re add the exact same files.

**Comment by ChrisMicro** [comment]
> I will cherry pick from this request, because the "Merge branch 'master'" commits are unnecessary noise.
> Also I don't want 2 commits that just remove then re add the exact same files.

The reason for this was that you mentioned that the BSB429 examples where not suitable to be used. Therefore I removed it. But than I saw that you have it in the repo so I had to add it again. There was some confusion.

**Comment by danieleff** [comment]
I cherrypicked the non-noise commits

**Comment by ChrisMicro** [comment]
OK, but I think one of a quite important issue is that the current implementation of your software for STM32F429 does only support PA0 as ADC input. 
I think it would be quite good to repair this issue quite soon because if anybody pulls the repo and will try other ADCs they will not work.

**Pull request closed without merging**
