### PR TITLE
Various compile warning/error fixes

### PR DESCRIPTION
**Pull request by grafalex82**
I tried to build my project with STM32Generic instead of STM32duino. I am using custom CMake-based build system, gcc 5.8.4 and -WAll. I got number of build errors and warnings.

Please check if my changes can be pushed to main repo

### CODE REVIEW

**Comment by danieleff** [comment]
Most of these are good.

- stm32_gpio_exti.c: that would break `attachInterrupt(...)`. I failed to change `stm32GpioClock` to `stm32GpioClockEnable` everywhere. The latter one is the correct.
- The `stm32_STM32F103CB.h` file is autogenerated, so the script would need to change. By the way, why did you remove the static from there, and comment out a row?

**Comment by grafalex82** [comment]
> stm32_gpio_exti.c: that would break attachInterrupt(...). I failed to change stm32GpioClock to stm32GpioClockEnable everywhere. The latter one is the correct.

I am not sure I understand what you are saying. What is wrong in my change?

> By the way, why did you remove the static from there

Because of this
```
D:\GRAFAL~1\Hobbies\Prog\MYPROJ~1\GPSLOG~1\Libs\STM32G~1\system\STM32F1\STM32_~1/stm32_STM32F103CB.h:98:13: warning: 'AF__HAL_AFIO_REMAP_TIM1_DISABLE' defined but not used [-Wunused-function]
 static void AF__HAL_AFIO_REMAP_TIM1_DISABLE(void) { __HAL_AFIO_REMAP_TIM1_DISABLE(); }
```

>  and comment out a row?

```
In file included from D:\Graf Alex\Hobbies\Prog\MyProjects\GPSLogger\Libs\STM32generic\cores\arduino\stm32\stm32_gpio_af.c:25:0:
D:\GRAFAL~1\Hobbies\Prog\MYPROJ~1\GPSLOG~1\Libs\STM32G~1\system\STM32F1\STM32_~1/stm32_STM32F103CB.h: In function 'AF__HAL_AFIO_REMAP_CAN_DISABLE':
D:\GRAFAL~1\Hobbies\Prog\MYPROJ~1\GPSLOG~1\Libs\STM32G~1\system\STM32F1\STM32_~1/stm32_STM32F103CB.h:93:45: warning: implicit declaration of function '__HAL_AFI
O_REMAP_CAN_DISABLE' [-Wimplicit-function-declaration]
 void AF__HAL_AFIO_REMAP_CAN_DISABLE(void) { __HAL_AFIO_REMAP_CAN_DISABLE(); }
```

Well, it seems this either a bug in stm32f1xx_hal_gpio_ex.h, or I did not catch the idea. Unlike other REMAP macros used in stm32_STM32F103CB.h and defined stm32f1xx_hal_gpio_ex.h there is no __HAL_AFIO_REMAP_CAN_DISABLE macro. I just found __HAL_AFIO_REMAP_CAN2_DISABLE, but not for CAN1. 

I am not sure what to do with this macro, so I just commented it for now to move forward. Perhaps I should add a comment there.

**Comment by grafalex82** [comment]
I added few more warning fixes:
- UNUSED macro in syscall.c conflicts with one in stm32f1xx_hal_def.h
Since they supposed to be used in different way (first one in function declaration, second - in the body) I decided to rename macro in syscall.c
- wrong type conversions between char* and unsigned char*

**Comment by danieleff** [comment]
UNUSED: would it be better just to remove the 5 rows with `#define UNUSED(x)` inside syscalls.c? I guess the two UNUSED macros do the same.

Edit: hmm it seems they do not do the same...

**Comment by grafalex82** [comment]
Correct, they have different semantics. Though it is possible to use HAL's UNUSED in a way they use it:

```
__weak void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin)
{
  UNUSED(GPIO_Pin);
}
```

**Pull request merged**
